#!/bin/sh
time_format='%l:%M %p'
date_format='%d %b, %Y'

# Start flavours
blank="#28282855"
text="#ebdbb2"
dark="#282828"
default="#fabd2fcc"
wrong="#fb4934bb"
verifying="#b8bb26cb"
type="#d65d0e"
delete="#cc241d"
# End flavours

prompt="Lock Screen"
options=(
    "lock"
    "daemon"
)

i3lock \
    --clock \
    --screen 1 \
    --ignore-empty-password \
    --pass-media-keys --pass-screen-keys --pass-volume-keys \
    \
    --time-str="$time_format" --date-str="$date_format" \
    --greeter-text="Type password to unlock..." \
    --time-pos="w-w/2:y+200" --date-pos="tx:ty+50" \
    --layout-pos="ix:iy+100" \
    \
    --radius=200 --ring-width=10 \
    --time-size=120 --date-size=32 --layout-size=22 \
    --keylayout=2 \
    \
    --color=$blank \
    --time-color=$text --date-color=$text --greeter-color=$text --layout-color=$text --modif-color=$text         \
    \
    --separator-color=$default --line-color=$blank \
    --keyhl-color=$type --bshl-color=$delete \
    --ring-color=$default      --inside-color=$blank        \
    --ringver-color=$verifying --insidever-color=$verifying --verif-color=$dark          \
    --ringwrong-color=$wrong   --insidewrong-color=$wrong   --wrong-color=$dark
