#!/usr/bin/env bash
declare -a options

wall_dir="$(xdg-user-dir PICTURES)/wallpapers"
mkdir -p "${wall_dir}"

autostart_script="$XDG_CONFIG_HOME/autostart-scripts/autostart.sh"
autostart_script_org="$XDG_CONFIG_HOME/README.org"

screens=$(xrandr | grep -e "\sconnected" | wc -l)

prompt="Wallpaper Category"
options=($(ls $wall_dir --hide="*.*"))

updateAutostart() {
    sed -i "s/\(.*dm-wallpaper\).*$/\1 $1 \&/" $autostart_script
    sed -i "s/\(.*dm-wallpaper\).*$/\1 $1 \&/" $autostart_script_org
}

setRandomWallpaper() {
    for (( i = 0; i < $screens; i++ )); do
        echo nitrogen --set-zoom-fill --random --head=$i $wall_dir/$1/
        nitrogen --set-zoom-fill --random --head=$i $wall_dir/$1/
    done

    # Comment out this line if you don't use an autostart script to set random wallpapers using this dmscript
    updateAutostart "$1"
}

[ ! $# -eq 0 ] && setRandomWallpaper $1 && exit

# Prompt the user
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p "${prompt}")

# Act on user selection
[ $choice ] && setRandomWallpaper $choice
