#!/bin/sh
TIME_FORMAT='%l:%M %p'
DATE_FORMAT='%d %b, %Y'

BLANK='#28282855'
TEXT='#ebdbb2'
DARK='#282828'
DEFAULT='#fabd2fcc'
WRONG='#fb4934bb'
VERIFYING='#b8bb26cb'
TYPE='#d65d0e'
DELETE='#cc241d'

i3lock \
    --clock \
    --screen 1 \
    --ignore-empty-password \
    --pass-media-keys --pass-screen-keys --pass-volume-keys \
    \
    --time-str="$TIME_FORMAT" --date-str="$DATE_FORMAT" \
    --greeter-text="Type password to unlock..." \
    --time-pos="w-w/2:y+200" --date-pos="tx:ty+50" \
    --layout-pos="ix:iy+100" \
    \
    --radius=200 --ring-width=10 \
    --time-size=120 --date-size=32 --layout-size=22 \
    --keylayout=2 \
    \
    --color=$BLANK \
    --time-color=$TEXT --date-color=$TEXT --greeter-color=$TEXT --layout-color=$TEXT --modif-color=$TEXT         \
    \
    --separator-color=$DEFAULT --line-color=$BLANK \
    --keyhl-color=$TYPE --bshl-color=$DELETE \
    --ring-color=$DEFAULT      --inside-color=$BLANK        \
    --ringver-color=$VERIFYING --insidever-color=$VERIFYING --verif-color=$DARK          \
    --ringwrong-color=$WRONG   --insidewrong-color=$WRONG   --wrong-color=$DARK          \
