#!/usr/bin/env bash
NOTIF_COUNT_DISPLAYED=$(dunstctl count displayed)
NOTIF_COUNT_HISTORY=$(dunstctl count history)
NOTIF_COUNT_WAIT=$(dunstctl count waiting)

execute_choice () {
    if [[ $1 == 'recents' ]]; then
        for ((i = 1; i <= $NOTIF_COUNT_HISTORY; i++));
        do
            dunstctl history-pop
        done

    elif [[ $1 == 'close' ]]; then dunstctl close
    elif [[ $1 == 'clear' ]]; then dunstctl close-all
    else dunstctl context
    fi
}

dmenu_prompt="Notifications"

declare -a options=(
    "Show recent"
    "Close"
    "Close all"
    "Context menu"
)

if [ ! $# -eq 0 ]; then execute_choice $1
else
    # Piping the above array into rofi -dmenu.
    # We use "printf '%s\n'" to format the array one item to a line.
    choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p "${dmenu_prompt}")
fi

case $choice in
    'Show recent') execute_choice recents ;;
    'Close') execute_choice close ;;
    'Close all') execute_choice close-all ;;
    'Context menu') execute_choice context ;;
esac
