#!/usr/bin/env bash
#
# Description: manage dunst notifications
# Dependencies: rofi -dmenu, dunst

NOTIF_COUNT_DISPLAYED=$(dunstctl count displayed)
NOTIF_COUNT_HISTORY=$(dunstctl count history)
NOTIF_COUNT_WAIT=$(dunstctl count waiting)



dmenu_prompt="Notifications"

declare -a options=(
    "Show recent"
    "Close"
    "Close all"
    "Context menu"
)

choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p "${dmenu_prompt}")

case $choice in
    'Show recent')
        for ((i = 1; i <= $NOTIF_COUNT_HISTORY; i++));
        do
            dunstctl history-pop
        done
        ;;
    'Close')
        dunstctl close
        ;;
    'Close all')
        dunstctl close-all
        ;;
    'Context menu')
        dunstctl context
        ;;
esac
