#!/usr/bin/env bash
# Specifying a directory with wallpapers and make sure it exists
wall_dir=~/Pictures/wallpapers
mkdir -p "${wall_dir}"

# get the number of connected screens
screens=$(xrandr | grep -e "\sconnected" | wc -l)

dmenu_prompt="Wallpaper Category"

setRandomWallpaper(){
    if [ -z "$1" ]; then
        return
    fi

    for (( i = 0; i < $screens; i++ )); do
        nitrogen --set-zoom-fill --random --head=$i $wall_dir/$1/
    done
}

if [ ! $# -eq 0 ]; then setRandomWallpaper $1

else
    choice=$(\ls $wall_dir --hide="*.*" | rofi -dmenu -i -p "${dmenu_prompt}")
    setRandomWallpaper $choice
fi
