#!/usr/bin/env bash
#
# Script name: dmwallpaper
# Description: set a random wallpapers
# Dependencies: nitrogen, xrandr


# path to wallpapers directory
wall_dir=~/Pictures/wallpapers

# get the number of connected screens
screens=$(xrandr | grep -e "\sconnected" | wc -l)


setRandomWallpaper(){
  if [ ! -z "$1" ]; then
    for (( i = 0; i < $screens; i++ )); do
      nitrogen --set-zoom-fill --random --head=$i $wall_dir/$1/
    done
  fi
}


if [ $# -eq 0 ]; then
  # Piping the wallpaper subfolders into rofi -dmenu.
  choice=$(\ls $wall_dir --hide="*.*" | rofi -dmenu -i -p 'Wallpaper Category')
  setRandomWallpaper $choice
else
  setRandomWallpaper $1
fi

