#!/usr/bin/env bash
# environment variables ________________________________________________________

# variables ====================================================================
scripts_dir="$HOME/.local/bin"

# options ----------------------------------------------------------------------
target="$1"

# functions ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
function get_default_output() {
    "$scripts_dir"/audioctl.sh get default
}

function list_outputs() {
    "$scripts_dir"/audioctl.sh list outputs
}

function switch_output() {
    output="$1"
    "$scripts_dir"/audioctl.sh switch "$output"
}

# prompt _______________________________________________________________________
prompt="$(get_default_output)"
dmenu="wofi --dmenu -p ${prompt}"

# setup ________________________________________________________________________
[[ ! $all_players =~ $target ]] && echo "[error]: no player '$target' found.
available players:
$all_players " && exit 1

[ "$target" ] && switch_output "$target" && exit 0

choice=$(printf '%s\n' "$(list_outputs)" | $dmenu) || exit 0

# main *************************************************************************
switch_output "$choice"
