#!/usr/bin/env bash

# variables --------------------------------------------------------------------
position='bottom' # tracking process

prompt="screenkey"
options=(
    "toggle"
    "swap-position"
)

# functions --------------------------------------------------------------------
key_grabber() {
    case "$1" in
        toggle) toggle_grabber;;
        "swap-position") swap_position;;
        *) echo Invalid input;;
    esac
}

toggle_grabber() {
    if pgrep -x screenkey > /dev/null
    then killall screenkey
    else screenkey --position $position
    fi
}

refresh() {
    if pgrep -x screenkey > /dev/null
    then killall screenkey && screenkey --position $position
    else screenkey --position $position
    fi
}

swap_position() {
    position='top'
    refresh
}

# setup ------------------------------------------------------------------------

# execution ====================================================================
# check if any arguments were passed to the script to avoid triggering dmenu
if [ ! $# -eq 0 ]; then
    # execute script without presenting dmenu to the user if an argument was
    # passed
    key_grabber "$1"

# if no arguments were passed, present dmenu to user printf '%s\n' is used to
# format the array one item to a line to feed to dmenu
else
    # prompt the user
    choice=$(printf '%s\n' "${options[@]}" | wofi --dmenu -p "${prompt}")

    [ "$choice" ] && key_grabber "$choice"
fi
