#!/usr/bin/env bash
declare -a options

# variables
#-------------------------------------------------------------------------------
prompt="Notifications"
options=(
    "Show recent"
    "Show few recents"
    "Close"
    "Close all"
    "Context menu"
)

notif_count_history=7
# notif_count_history=$(dunstctl count history)
notif_count_displayed=$(dunstctl count displayed)
notif_count_wait=$(dunstctl count waiting)

# functions
#-------------------------------------------------------------------------------
execute_choice() {
    case $1 in
        close) dunstctl close;;
        clear) dunstctl close-all;;
        recent) dunstctl history-pop;;
        recents)
            for ((i = 1; i <= notif_count_history; i++));
            do
                dunstctl history-pop
            done
            ;;
        *) dunstctl context;;
    esac
}

# setup
#-------------------------------------------------------------------------------
# execute script without presenting dmenu to the user if any argument was passed
[ ! $# -eq 0 ] && execute_choice "$1" && exit

# Present dmenu to user with options defined in the [[#dmenu][DMenu]] section
# printf '%s\n' is used to format the array one item to a line to feed to dmenu
choice=$(printf '%s\n' "${options[@]}" | wofi --dmenu -p "${prompt}")

# execution
#===============================================================================
case $choice in
    'Show recent') execute_choice recent ;;
    'Show few recents') execute_choice recents ;;
    'Close') execute_choice close ;;
    'Close all') execute_choice close-all ;;
    'Context menu') execute_choice context ;;
esac
