#!/usr/bin/env bash
declare -a options

# environment variables --------------------------------------------------------
# define LOCKER in .xpwofile to set to different locker program
case $XDG_SESSION_TYPE in
    x11) LOCKER="$HOME/.config/i3lock/i3lock.sh" ;;

    wayland)
        case $XDG_SESSION_DESKTOP in
            Hyprland) LOCKER="hyprlock" ;;
            *) LOCKER="swaylock" 1 ;;
        esac ;;

    *) exit 1 ;;
esac

# variables --------------------------------------------------------------------
# use notify-send if run in dumb term
output="echo"
if [[ ${TERM} == 'dumb' ]]; then
    output="notify-send"
fi

# functions --------------------------------------------------------------------
function yesno () {
    # shellcheck disable=SC2005
    echo "$(echo -e "No\nYes" | wofi --dmenu -p "${1}")"
}

declare -a managers=(
    "awesome"
    "bspwm"
    "dwm"
    "spectrwm"
    "xmonad"
    "qtile"
)

prompt="Shutdown menu"
declare -a options=(
    "Suspend"
    "Reboot"
    "Shutdown"
    "Logout"
    "Lock screen"
    "Disconnect Controllers"
    "Quit"
)

function execute_choice () {
    if [[ $1 == 'lock' ]]; then ${LOCKER}
    elif [[ $1 == 'reboot' ]]; then systemctl reboot
    elif [[ $1 == 'poweroff' ]]; then systemctl poweroff
    elif [[ $1 == 'suspend' ]]; then systemctl suspend
    elif [[ $1 == 'controller' ]]; then ~/.local/bin/disconnect-controller.sh || exit 0
    elif [[ $1 == 'quit' ]]; then ${output} "Program terminated." && exit 0
    else ${output} "Program terminated." && exit 0
    fi
}

# setup ------------------------------------------------------------------------
# execute script without presenting dmenu to the user if any argument was passed
[ ! $# -eq 0 ] && execute_choice "$1" && exit 0

# Present dmenu to user with options defined in the [[#dmenu-1][DMenu]] section
# printf '%s\n' is used to format the array one item to a line to feed to dmenu
# prompt the user
choice=$(printf '%s\n' "${options[@]}" | wofi --dmenu -p "${prompt}")

# execution ====================================================================
case $choice in
    'Logout')
        if [[ $(yesno "Logout?") == "Yes" ]]; then
            for manager in "${managers[@]}"; do
                killall "${manager}" || ${output} "Process ${manager} was not running."
            done
        else
            ${output} "User chose not to logout." && exit 1
        fi
        ;;
    'Lock screen') execute_choice lock ;;
    'Reboot')
        if [[ $(yesno "Reboot?") == "Yes" ]]; then
            execute_choice reboot
        else
            ${output} "User chose not to reboot." && exit 0
        fi
        ;;
    'Shutdown')
        if [[ $(yesno "Shutdown?") == "Yes" ]]; then
            execute_choice poweroff
        else
            ${output} "User chose not to shutdown." && exit 0
        fi
        ;;
    'Suspend')
        if [[ $(yesno "Suspend?") == "Yes" ]]; then
            execute_choice suspend
        else
            ${output} "User chose not to suspend." && exit 0
        fi
        ;;
    "Disconnect Controllers")
        ~/.local/bin/disconnect-controller.sh
        ;;
    'Quit') execute_choice quit ;;
    # It is a common practice to use the wildcard asterisk symbol (*) as a final
    # pattern to define the default case. This pattern will always match.
    *)
        exit 0
        ;;
esac
