#!/usr/bin/env bash
set -euo pipefail

prompt="Screenshot"
options=(
    "Monitor"
    "Area"
    "Window"
    "Desktop"
    "TV"
)

main() {
    scope="$1"
    case "$scope" in
        "Monitor") ~/.local/bin/screenshot.sh monitor ;;
        "Area") ~/.local/bin/screenshot.sh area ;;
        "Window") ~/.local/bin/screenshot.sh window ;;
        "Desktop") ~/.local/bin/screenshot.sh desktop ;;
        "TV") ~/.local/bin/screenshot.sh tv ;;
        *) echo Invalid input;;
    esac
}

# execute script without presenting dmenu to the user if any arguments were
# passed to the script
[ ! $# -eq 0 ] && main $1 && exit

# if no arguments were passed, present dmenu to user
choice=$(printf '%s\n' "${options[@]}" | rofi -dmenu -i -p "${prompt}")

# act on user selection
[ $choice ] && main "$choice"
