#!/usr/bin/env bash
declare -a options

[ ! "$XDG_PICTURES_DIR" ] && export XDG_PICTURES_DIR="$HOME/Pictures"

wallpapers_dir="$XDG_PICTURES_DIR/wallpapers"

prompt="Wallpaper Category"
options=("$(ls "$wallpapers_dir" --hide="*.*")")

choice=$(printf '%s\n' "-refresh" "${options[@]}" | wofi --dmenu -p "${prompt}")

case $choice in
    '') exit 1 ;;
    '-refresh') ~/.local/bin/set-wallpaper.sh ;;
    *) ~/.local/bin/set-wallpaper.sh "$choice" ;;
esac
