#!/usr/bin/env bash
declare -a options

if [ ! "$XDG_PICTURES_DIR" ]; then
    export XDG_PICTURES_DIR="$HOME/pictures"
fi

wallpapers_dir="$XDG_PICTURES_DIR/wallpapers"

prompt="Wallpaper Category"
options=("$(ls "$wallpapers_dir" --hide="*.*")")

choice=$(printf '%s\n' "-refresh" "${options[@]}" | rofi -dmenu -i -p "${prompt}")

case $choice in
    '-refresh') ~/.local/bin/set-wallpaper.sh ;;
    *) ~/.local/bin/set-wallpaper.sh "$choice" ;;
esac
